### PR TITLE
Add support for notebook document completions

### PR DESCRIPTION
**Pull request by smacke**
In this PR, we add support for notebook document completions, so that completions can work across cell boundaries. The implementation is straightforward and closely follows that for definitions.

Test plan: added a unit test that fails without the changes in this PR and passes with the changes.

### CODE REVIEW

**Comment by tkrabel** [comment]
@ccordoba12 can you TAL at this PR? :)

**Comment by ccordoba12** [comment]
Thanks for the ping @tkrabel! Will do right away.

**Review by ccordoba12 — APPROVED** [review]
As you said @smacke, this is pretty straightforward, so it looks good to me.

**Comment by smacke** [comment]
Awesome TY!

**Pull request merged**
