### PR TITLE
Bump flake8 to version 7

### PR DESCRIPTION
**Pull request by bnavigator**
Flake 8 v7.0.0 has been released. Try to keep up with it

### CODE REVIEW

**Comment by doolio** [comment]
@bnavigator @ccordoba12 could the issue this PR resolves be ultimately resolved by using something like dependabot?

**Review by ccordoba12 — APPROVED** [review]
Thanks @bnavigator!

**Comment by ccordoba12** [comment]
> could the issue this PR resolves be ultimately resolved by using something like dependabot?

I guess, but I haven't used it before.

**Comment by doolio** [comment]
@ccordoba12 it seems dependabot committed to the project in the past (perhaps before the community forked it). It seems looking at the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) that:

image

**Comment by ccordoba12** [comment]
I don't have time to deal with that, sorry.

**Comment by doolio** [comment]
Sure, I can understand that. I suggested it as a way perhaps to reduce the load on you.

**Pull request merged**
