### PR TITLE
setup isort & black, introduce pre-commit

### PR DESCRIPTION
**Pull request by syphar**
As discussed. 

I kept the configuration & the actual reformat separate. 

- the new ignores (`E203`, `W503`) are due to https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated 
- personally I like using pre-commit for these things so it's run locally with the same settings. 
- coming the current config I assumed a preferred max-line-len of 120 
- when merged, I would also add the commit ID to a new `.git-blame-ignore-revs` to remove it from eventual `git blame` results. 

Of course we can discuss settings, or discard this completely if you don't like the format :)

### CODE REVIEW

**Comment by syphar** [comment]
btw, if feels like the readabilty could benefit from a smaller maximum line length (100?), but that's up to you

**Comment by rchl** [comment]
If the majority of the code uses single quotes already then don't you think that the configuration should be aligned with that to introduce least amount of noise to the PR and follow the preference of the main contributors?

**Comment by syphar** [comment]
that's a design question, and totally up to the contributors. Its configurable (via `--skip-string-normalization`). 

IMO the main advantage of black is the opinionated style, but that's just me.

**Comment by rchl** [comment]
Another argument for single quotes could be that it's just easier to type on most popular keyboard layouts (US, EN) since it's just one key instead of two.

That said, if the quotes will be auto-fixed then maybe it doesn't matter. As you said, up to main contributors and I'm not one of them.

**Comment by ccordoba12** [comment]
Closing as superseded by #419. Precommit can be added in another PR.

**Pull request closed without merging**
