### PR TITLE
Add mccabe setting to flake8

### PR DESCRIPTION
**Pull request by baco**
Flake8 can also wrap mccabe complexity linter. In order to support those flags, added the corresponding configuration key to flake8 plugin in Python LSP server.

If such option is not available mccabe linter is never invoked, because default value for mccabe threshold in flake8 is `-1` which means “deactivated”

### CODE REVIEW

**Comment by doolio** [comment]
@ccordoba12 any chance this could be merged?

**Comment by ccordoba12** [comment]
Sorry, I missed this one completely. @baco, do you have time to fix the merge conflict? Or do you prefer for me to do it?

**Comment by baco** [comment]
@ccordoba12 I'll look into it later today :-)

**Comment by baco** [comment]
@ccordoba12 There, I've solved the conflict with the branch

**Review by ccordoba12 — APPROVED** [review]
Looks good to me. Thanks for your contribution @baco!

**Pull request merged**
