### PR TITLE
Handle VIRTUAL_ENV when running flake8

### PR DESCRIPTION
**Pull request by shosca**
Uses VIRTUAL_ENV if its in environment and converts executables to absolute paths

lsp config reference: https://github.com/shosca/dotfiles/blob/master/nvim/.config/nvim/ftplugin/python.lua

### CODE REVIEW

**Comment by brandonwillard** [comment]
Isn't this supposed to be handled by the runtime environment?   More specifically, when an environment is active, `PATH` is usually updated to reflect which `flake8` should be used.

Adding something like this seems like it would conflict with those standard expectations, and&mdash;for example&mdash;subvert `PATH` or any other means of determining the executable.

**Comment by shosca** [comment]
> environment is active

Yes, though that would require the editor to run in activated virtual env. I am sure there will be lazy devs (like me :sweat_smile:) that doesn't activate a virtual env for their editors: https://github.com/neovim/nvim-lspconfig/issues/500

Also, `pylsp` itself actually allows controlling this via `VIRTUAL_ENV` via [jedi](https://github.com/davidhalter/jedi/blob/dcea842ac237b51263c29a252dba9b650fc799ff/jedi/api/environment.py#L144) i believe.

**Comment by shosca** [comment]
This pr is not needed anymore, for people that hit the issue of handling the virtual env with neovim lsp you basically need some function to get you the virtualenv path:

```lua
function M.get_python_venv()

    if vim.env.VIRTUAL_ENV then return vim.env.VIRTUAL_ENV end

    local match = vim.fn.glob(lsputil.path.join(vim.fn.getcwd(), 'Pipfile'))
    if match ~= '' then return vim.fn.trim(vim.fn.system('PIPENV_PIPFILE=' .. match .. ' pipenv --venv')) end

    match = vim.fn.glob(lsputil.path.join(vim.fn.getcwd(), 'poetry.lock'))
    if match ~= '' then return vim.fn.trim(vim.fn.system('poetry env info -p')) end
end
```

then in your lspconfig setup for pylsp:
```lua
local lsputil = require('lspconfig/util')
local venv = require('utils').get_python_venv()
lspconfig.pylsp.setup {
    cmd = {"pylsp", "-v"},
    cmd_env = {VIRTUAL_ENV = venv, PATH = lsputil.path.join(venv, 'bin') .. ':' .. vim.env.PATH},
    ... rest of your pylsp config ...
}

```

**Comment by ccordoba12** [comment]
Closing then.

**Pull request closed without merging**
