### PR TITLE
Remove built-in `rope_rename` plugin

### LINKED ISSUE #255: Confusion about rename support
I can see some references to those:
 - `jedi_rename`: https://cs.github.com/python-lsp/python-lsp-server?q=jedi_rename
 - `rope_rename`: https://cs.github.com/python-lsp/python-lsp-server?q=rope_rename

But none of them is documented.

When I try to rename in a simplest of projects, without setting any `jedi_rename` or `rope_rename` options, it appears to work for me ([but not for someone else, not sure why yet](https://github.com/sublimelsp/LSP-pylsp/issues/86)).

With `"pylsp.plugins.rope_rename.enabled": true` it appears to work also but incorrectly (the file path is not specified so ST creates new buffer instead of modifying existing one). The log is:

```
:: --> LSP-pylsp textDocument/rename(6): {'position': {'character': 1, 'line': 0}, 'textDocument': {'uri': 'file:///Users/rafal/Downloads/tpy/test.py.py'}, 'workDoneToken': 'wd6', 'newName': 'xyx'}
:: <<< LSP-pylsp 6: {'documentChanges': [{'textDocument': {'uri': 'file:///test.py.py', 'version': None}, 'edits': [{'newText': "xyx = '111'\nyyy = xyx + '222'", 'range': {'end': {'character': 0, 'line': 2}, 'start': {'character': 0, 'line': 0}}}]}]}
```

So in conclusion:
 - `rope_rename` is not documented and also seems broken
 - `jedi_rename` doesn't have an option and seems enabled by default - is that right?

I guess my point is:
 - should `rope_rename` be documented, fixed or removed?
 - should there be some mention of rename functionality being supported?

### PR DESCRIPTION
**Pull request by doolio**
This functionality is better served by the pylsp-rope plugin.

Fixes #255

### CODE REVIEW

**Comment by krassowski** [comment]
That would be a major version bump, right? Some downstreams depend on the rope rename support being there by default.

**Comment by doolio** [comment]
Yes, I should think so. This PR relates to this [comment](https://github.com/python-lsp/python-lsp-server/issues/255#issuecomment-1900774440) from @ccordoba12 who I trust will decide when this could be considered for release with the appropriate version bump.

**Comment by ccordoba12** [comment]
> That would be a major version bump, right? Some downstreams depend on the rope rename support being there by default.

A couple of questions:

* Do you know which projects depend on it?
* I think there shouldn't be major issues for downstream projects because the only thing they should be doing is enabling `rope_rename` with a config option, which would stop working. But renames could be handled by enabling `jedi_rename` instead.

**Comment by Shane-XB-Qian** [comment]
> > That would be a major version bump, right? Some downstreams depend on the rope rename support being there by default.
> 
> A couple of questions:
> 
> * Do you know which projects depend on it?
> * I think there shouldn't be major issues for downstream projects because the only thing they should be doing is enabling `rope_rename` with a config option, which would stop working. But renames could be handled by enabling `jedi_rename` instead.

if it was enabled by default, then could you also make this refactor keep 'rename' feat be enabled by default? though it would be on 'jedi'.
// since perhaps someone maybe no 'rope' installed, or not like (or cannot) to install 'rope'.

-- 
shane.xb.qian

**Comment by doolio** [comment]
> if it was enabled by default

No, it is not enabled by default 

https://github.com/python-lsp/python-lsp-server/blob/d72690557f8997d13027802b639fb142b7304ba7/pylsp/plugins/rope_rename.py#L15-L17

and not even listed as a configuration option in [CONFIGURATION.md](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) which is what brought it to my attention.

Edit: Nor for that matter is `jedi_rename`!

**Comment by lieryan** [comment]
`rope_rename` is not currently enabled by default, so the only configuration that breaks is for people who explicitly enabled `rope_rename`, which I don't suppose there will be many people using them.

`pylsp-rope` currently do not support renaming. I can add this to pylsp-rope, but will need to make sure that the version constraints is such that people don't install pylsp-rope with rename support on older python-lsp-server that also has conflicting rename support.

**Comment by ccordoba12** [comment]
> rope_rename is not currently enabled by default, so the only configuration that breaks is for people who explicitly enabled rope_rename, which I don't suppose there will be many people using them.

Agreed. That's why I think if we make a note in the release notes about the removal of that plugin and that people can switch to `jedi_rename` now and `pylsp-rope` in the future should be enough.

> pylsp-rope currently do not support renaming. I can add this to pylsp-rope

That would be great, thanks @lieryan!

> but will need to make sure that the version constraints is such that people don't install pylsp-rope with rename support on older python-lsp-server that also has conflicting rename support.

Ok, so that means you probably need to have this in a published release of `python-lsp-server` so that `pylsp-rope` can depend on it, right?

**Review by ccordoba12 — APPROVED** [review]
Thanks for your help with this @doolio!

**Comment by doolio** [comment]
No problem. I presume nothing further is required from me with this PR?

**Comment by ccordoba12** [comment]
Nop, it isn't.

**Pull request merged**
