### PR TITLE
Restore the JSON schema, add human-readable configuration

### LINKED ISSUE #24: Where to put structured documentation now?
Now removed `vscode-client` had `package.json` which included a structured documentation of configuration options. Should we retain this file (possibly in a different place/under a different name)?

### PR DESCRIPTION
**Pull request by krassowski**
Closes #24. This takes the best of both words:
- keeps machine-readable configuration schema, making it easy to adapt it for settings validation (if we would want to do so in the future)
- auto-generates human-readable configuration documentation roughly following the tabular format suggested in https://github.com/python-lsp/python-lsp-server/issues/24#issuecomment-829355956 to match the current README of `pyls-spyder` plugin
- checks validity of the schema and ensures the markdown and schema version remain in sync

In schema itself:
- updated the keys with `pylsp` over `pyls`
- fixed one incorrect type caught thanks to the schema validation
- removed no longer needed `pylsp.executable` (it was only used in the vscode-client)

### CODE REVIEW

**Comment by krassowski** [comment]
Ready for review.

**Comment by raprocks** [comment]
haha was doing this locally. nciely done!

**Comment by krassowski** [comment]
Feel very welcome to review and suggest improvements.

**Comment by andfoy** [comment]
Thanks for tour help with this one!

**Review by andfoy — APPROVED** [review]

**Comment by raprocks** [comment]
nice.

**Pull request merged**
