### PR TITLE
Fix progress reporting with autoimport plugin

### LINKED ISSUE #529: Autoimports: sqlite3.OperationalError: database is locked
Hi. My autoimports didn't work well, so i tried to inspect my problem. All i found is error logs from lsp server like this:

```
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	'Exception in thread Thread-1 (_reload_cache):\nTraceback (most recent call last):\n  File "/home/danya/.pyenv/versions/3.12.1/lib/python3.12/threading.py", line 1073, in _bootstrap_inner\n'
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	"    self.run()\n"
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	'  File "/home/danya/.pyenv/versions/3.12.1/lib/python3.12/threading.py", line 1010, in run\n'
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	"    self._target(*self._args, **self._kwargs)\n"
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	'  File "/home/danya/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.12/site-packages/pylsp/plugins/rope_autoimport.py", line 71, in _reload_cache\n'
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	'    autoimport.generate_cache(task_handle=task_handle, resources=resources)\n  File "/home/danya/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.12/site-packages/rope/contrib/autoimport/sqlite.py", line 368, in generate_cache\n'
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	'    self._execute(\n  File "/home/danya/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.12/site-packages/rope/contrib/autoimport/sqlite.py", line 643, in _execute\n'
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	"    return self.connection.execute(query._query, *args, **kwargs)\n"
[ERROR][2024-02-14 11:55:21] .../vim/lsp/rpc.lua:734	"rpc"	"/home/danya/.local/share/nvim/mason/bin/pylsp"	"stderr"	"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsqlite3.OperationalError: database is locked\n"
```

No related problems was found, except of recently works on something similar like #474 and #499

Any thoughts? I'm not a pylsp developer, so help would be really appreciated.

### PR DESCRIPTION
**Pull request by last-partizan**
This is temporary fix, until someone can make proper fix by resolving issue with thread, seems like it just hungs indefinitely instead of reporting progress.

Also, this thread does not exit properly, and pylsp does not exit after editor is closed.

Fixes #529.
Refs #374

### CODE REVIEW

**Comment by last-partizan** [comment]
@tkrabel i'm tagging you, maybe you have better idea how to fix this.

Was it working when you tested it?

Right now seems like thread just hangs indefinitely and not exit.

**Comment by tkrabel** [comment]
@last-partizan thanks for the git bisect and for tagging me. I did a unit an manual test to make sure everything worked, but I might have missed something. Making the progress report single threaded seems to be a good tactical fix. I will investigate how I can solve the issue without losing the non-blocking feature.

**Comment by ccordoba12** [comment]
@tkrabel, are you ok with merging this one and release 1.10.1 while you try to find a better solution?

**Comment by tkrabel** [comment]
@ccordoba12 yes that LGTM

**Comment by rodda-kyusu** [comment]
Was able to test this PR locally and confirmed that the issue present in https://github.com/python-lsp/python-lsp-server/issues/529 stopped occurring 🙌

**Review by ccordoba12 — APPROVED** [review]
Thanks for your contribution @last-partizan!

**Pull request merged**
