### PR TITLE
Add `DiagnosticTag` support

### LINKED ISSUE #144: Add `DiagnosticTag` tags for pylint, pycodestyle, and flake8
As a follow up to #142 we can now add `tags` to diagnostics for specific plugins.
This would likely need to be based on matching the error codes.

- pylint (https://pylint.pycqa.org/en/v2.12.2/technical_reference/features.html):
  - Deprecated:
     - W0402: Uses of a deprecated module %r
      - W1505: Using deprecated method %s()
     - W1511: Using deprecated argument %s of method %s()
     - W1512: Using deprecated class %s of module %s
     - W1513: Using deprecated decorator %s()
  - Unnecessary:
     - W0611: Unused import %s
     - W0612: Unused variable %r
     - W0613: Unused argument %r
     - W0614: Unused import %s from wildcard import
     - W1304: unused-format-string-argument
- pycodestyle (https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes):
   - Deprecated: all codes starting with W6
- flake8 (https://flake8.pycqa.org/en/latest/user/error-codes.html):
   - Unnecessary:
     - F401: module imported but unused
     - F504: % format unused named arguments
     - F522: .format(...) unused named arguments
     - F523: .format(...) unused positional arguments

I think it's worth the effort, but wanted to first see if you agree. Happy to make a PR with the changes.

### PR DESCRIPTION
**Pull request by krassowski**
Closes #144.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please rebase on top of the latest `develop` to get the fix to our tests in PR #231.

**Comment by ccordoba12** [comment]
@krassowski, this has a conflict now.

**Comment by krassowski** [comment]
Resolved.

**Review by ccordoba12 — APPROVED** [review]
Thanks @krassowski!

**Pull request merged**
